theme = 'hugo-theme-stack'
enableGitInfo = true
title = "Blog personal"
date: 1989
topics:
  - "Sistema educativo"
  - "Política y poder"
  - "Instituciones"
  - "Cultura pública"
  - "Historia del presente"
actual_reads: 
- "Hobbes"
- "WatchMen"
- "Tiger"
x: "@phiLL3141"
languageCode = "es"
defaultContentLanguage = "es"

[author]
  name = "Andres Felipe Hurtado Agudelo"


[params]
  mainSections = ["post"]
  description = "Lo que rescato de mi diario"

  [params.sidebar]
    subtitle = "Lo que rescato de mi diario"

  [params.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"
