theme = 'hugo-theme-stack'
enableGitInfo = true
title = "[[Andrés Felipe Hurtado]]"
languageCode = "es"
defaultContentLanguage = "es"

[author]
  name = "Andrés Felipe Hurtado Agudelo"

[params]
  mainSections = ["post"]
  description = "Lo que rescato de mi diario"
  # Aquí he metido tus temas y lecturas para que Hugo no de error
  topics = ["Sistema educativo", "Política y poder", "Instituciones", "Cultura pública", "Historia del presente"]
  actual_reads = ["Hobbes", "WatchMen", "Tiger"]
  x_handle = "@phiLL3141"
  birth = "1989"

  [params.sidebar]
    subtitle = "Memoria."
    enabled = true
    local = true
    src = "img/avatar.jpg"
  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [params.sidebar]
    subtitle = "Lo que rescato de mi diario"

  [params.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"

    [outputs]
    home = ["HTML", "RSS", "JSON"]

[params.search]
    enabled = true
